### ISSUE TITLE
WpfHexaEditor.HexEditor causing Visual Studio, Application to lock up, spawning hundreds of threads

### ISSUE THREAD

**Issue by Mgamerz** [abbaye/WpfHexEditorControl#32] opened 2018-06-09 01:48 UTC
## Expected Behavior
While in designer view, Visual Studio should not lock up when WPFHexaEditor is visible. Having two blank HexEditor's should not seriously degrade application performance.

## Actual Behavior
I'm finding when a second HexEditor (the stable version) is shown on screen, performance of Visual Studio becomes very sluggish. While in app (and running), when I show a second HexEditor is loaded the performance of the application degrades significantly in both Visual Studio and app:
 - Mouse clicks are not reliably registered
 - Dragging the window updates maybe 2 times a second
 - Typing in visual studio xaml designer does not reliably work

## Steps to Reproduce the Problem
I am not 100% sure how reproducible this is in another setup. My setup is as follows.
  1. Put a hexeditor in a tabcontrol tab
  2. Put another hexaeditiro in another tab in the same tabcontrol
  3. When the second tab's tab control is visible, visual studio (and the running application) performance degrades to the point of near unusability.

I have had this issue for some time now, however it was killing visual studio performance signifcantly across the board. I have reported it as an issue with Visual Studio. They finally fixed some unresolved reference bugs in 15.7.3, however some Visual Studio developers looked at my project and took note of how many threads were being spawned by WPFHexaEditor.dll!WpfHexaEditor.Core.Caret.BlinkCaret. I have a thread on DeveloperCommunity for Visual Studio where they talk about it. https://developercommunity.visualstudio.com/comments/264723/view.html

As it stands I can't use this project as it is killing my application performance as well as the development environment when I'm in designer view. It's a good project, if this issue can be resolved I would love to continue using it.

**Comment by abbaye** [comment] 2018-06-18 21:22
I Will check this soon as possible Thank you

**Comment by romnous** [comment] 2018-07-24 10:36
hi @abbaye, im looking to use this control in an application im developing but this issue makes the control unusable. any update?

**Comment by abbaye** [comment] 2018-07-24 13:35
Hello @romnous sorry i Will check this issue the next weekend when i will go to home after camping :)

**Comment by abbaye** [comment] 2018-07-24 13:36
Are tout use the code version or binary from nuget ?

**Comment by romnous** [comment] 2018-07-25 08:02
i'm currently working with the version from nuget. later in the week i'll have time to try this out with the latest version on the master branch and i'll report back to you

**Comment by romnous** [comment] 2018-08-06 07:59
latest master is giving me the same issues. i'm also noticing i can't set focus to text fields or other editable controls on the same tab while the `HexEditor` is present

**Comment by abbaye** [comment] 2018-08-07 01:32
Ok i need to check this. I dont know why at this moment

**Comment by abbaye** [comment] 2018-08-25 15:01
I have checked but i can't reproduce bug.

**Comment by MrCzz** [comment] 2019-01-08 10:32
Hello Abbaye,

I created a small project which shown the issue with the WpfHexEditorControl. See attachment

It is a simple example project, which will be very slow when you try to change the:

```xaml
<TextBox Grid.Row="5" Grid.Column="1" Grid.ColumnSpan="2" VerticalAlignment="Center" Text="HEXEDITOR" Height="100" IsEnabled="False" />
```

with:

```xaml
<wpfHexaEditor:HexEditor Grid.Row="5" Grid.Column="1" Grid.ColumnSpan="2"  Width="Auto" Height="100" VerticalAlignment="Center" />
```

Compiled the latest master .NET Framework 4.5.1, compiling on .NET Framework 4.6.1. Hopes this helps you.

[HexaEditorCrashTest.zip](https://github.com/abbaye/WpfHexEditorControl/files/2736312/HexaEditorCrashTest.zip)

**Comment by abbaye** [comment] 2019-01-10 17:54
Hello MrCzz

Did you have tested with the lastest code ?

I Can't compile your code because the file TabViews/TabItem1.xaml are not in your ZIP

**Comment by MrCzz** [comment] 2019-01-11 07:41
Compiled with latest master in github version .NET 4.5.1. 

The nuget package only support .NET 4.7.1. andere I compile the code on .NET 4.6.1.

**Comment by abbaye** [comment] 2019-01-11 16:01
Ok I never tester control with tabcontrol. I think I have a bug with.

I need to check this :)

**Comment by MrCzz** [comment] 2019-01-28 15:13
Do you have a status update on this?

**Comment by abbaye** [comment] 2019-01-28 16:08
Not For now :( I have not time to check until I finished.my University session in April. Sorry for this. I make this project in my free time and is rare now :(

**Comment by abbaye** [comment] 2019-03-02 12:42
Hi MrCzz

I just tested with Visual Studio 2019 Prerelease 4 and i think the bug is now closed.

Can you test on your side and give me if you can an update on this

**Comment by abbaye** [comment] 2019-03-02 12:48
I have juste pushed a update of sample with tabcontrol support. I will add posibility to open new file in new tab control for make a better test

**Comment by abbaye** [comment] 2019-03-02 12:53
F#$k!! The bug just appear. I will check this !

**Comment by abbaye** [comment] 2019-03-02 13:23
The bug is now fixed !

I have make a check for checking when we use DesignerMode on the Caret class.

Now it's work fine.  Sorry for delay for correct this

**Comment by abbaye** [comment] 2019-03-02 13:45
I Think the bug is fixed.

please check on your side and give me an update on this

**Comment by MrCzz** [comment] 2019-03-04 08:32
Thank you, will test it.

**Comment by romnous** [comment] 2019-03-04 10:57
bug appears to be fixed here (.NET 4.6.1 using both VS2017 and Rider 2018.3.3)

**Comment by abbaye** [comment] 2019-03-04 12:11
GOOD! :)  Have a great day everybody

**Closed by abbaye** 2019-03-04 12:11 UTC
Labels: bug, help wanted
